export const fonts = {
  regular: 'LufgaRegular',
  medium: 'LufgaMedium',
  semiBold: 'LufgaSemiBold',
  bold: 'LufgaBold',
  extraBold: 'LufgaExtraBold',
  light: 'LufgaLight',
  extraLight: 'LufgaExtraLight',
  thin: 'LufgaThin',
  black: 'LufgaBlack',
  italic: 'LufgaItalic',
  mediumItalic: 'LufgaMediumItalic',
  semiBoldItalic: 'LufgaSemiBoldItalic',
  boldItalic: 'LufgaBoldItalic',
  extraBoldItalic: 'LufgaExtraBoldItalic',
  lightItalic: 'LufgaLightItalic',
  extraLightItalic: 'LufgaExtraLightItalic',
  thinItalic: 'LufgaThinItalic',
  blackItalic: 'LufgaBlackItalic',
};
